# Generated by Django 6.0 on 2026-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos_carteiras/')),
                ('validade', models.DateField()),
            ],
        ),
    ]
